### ISSUE TITLE
Antivirus warning for Trojan

### ISSUE THREAD

**Issue by NeunMonde** [TheWinABagel/ZenithAttributes#12]
After installing Zenith Attributes 0.2.1 and FakerLib 0.1.3, Windows Defender presented me with the following message:

![trojan1](https://github.com/TheWinABagel/ZenithAttributes/assets/129331127/fc7cfd41-8b0e-4101-b495-1211202f0f98)
![trojan2](https://github.com/TheWinABagel/ZenithAttributes/assets/129331127/2ca701a6-4fa8-4d93-9f37-8e3cca04a43d)

This could possibly be a false positive, however it might be useful to check it out anyways.

**Comment by TheWinABagel** [comment]
Whack
Apotheosis had the same issue, you can put it through virus total or smth if you really are worried, but the code is fully open source if you really need to check. A quick google also shows that windows defender has a lot of false positives with "wacatac.B!ml" so idk

**Comment by NeunMonde** [comment]
Alright, thank you!
