### ISSUE TITLE
Exception occurred in netty pipeline io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Faryzal2020** [TheWinABagel/ZenithAttributes#15]
I made a dedicated server for the Prominent II RPG 2 days ago and it works well, we made spawn building, add serverside mods and config everything, but some time after that this error spammed the logs and the logfile size would reach 1GB if it keep going for a few minutes.
So i tried MANY things to troubleshoot, and few hours after no sleep i found a temporary solution which is changing the server's port from 25565 to 25564. After that it works for a few hours and then the error shows up again.
Then i tried to make a new folder, run a vanilla fabric 0.14.25 for minecraft 1.20.1, vanilla works, then i add some mods that i think would be the problem until error shows up, then remove the mods one by one until i found the culprit.
The error reproduced with fabric 0.14.25 and i only installed zenith attributes 0.1.3 (that the modpack uses) and its dependencies.
[latest.log](https://github.com/TheWinABagel/ZenithAttributes/files/14730049/latest.log)

**Comment by cintreck** [comment]
what was the culprit then?

**Comment by Partonetrain** [comment]
why zenith attributes 0.1.3? Does this happen with 0.2.2?

**Comment by Faryzal2020** [comment]
my tests determined that zenith attributes was the culprit
the modpack (Prominence II) is using zenith attributes 0.1.3, idk if 0.2.2 would work because updating one mod usually requires to update many other things as well

**Comment by Partonetrain** [comment]
In my dev instance, the game prints `Unknown custom packed identifier: zenith_attributes:crit_particles` when CritParticleMessage.sendTo is called.

I believe the problem is that [ClientPlayNetworking.registerGlobalReceiver](https://fabricmc.net/wiki/tutorial:networking#receiving_a_packet_on_the_game_client) is never called, but networking code is fairly new to me so I'm not sure

**Comment by Faryzal2020** [comment]
google search results many people with this error except they're clientside error when trying to connect to a server, meanwhile my error is on the server side, spamming the console until the server stopped responding.
i haven't find any solutions for this except changing the game server's port number, which is a temporary duct tape fix because sometimes the error would come back in a few days and we have to change the port number again.

**Comment by TheWinABagel** [comment]
0.2.3 brings that pr, *might*(??) be fixed... 0.1.3 is a really old version though so IDK if it's even still a problem...
