### ISSUE TITLE
ZenithAttributes 0.2.2 crashes when using AllStats inlay gems.

### ISSUE THREAD

**Issue by AluLescano** [TheWinABagel/ZenithAttributes#16]
Hello! I was trying to inlay the Perfect Gem of the Royal Family into a helmet for the 20% All Stats bonus, and the game crashes before I can even grab the item from the Smithing Table.

I took the time to export the .jar file and checked which dependency was giving the 

**_"java.lang.NoSuchMethodError: 'dev.shadowsoffire.attributeslib.util.AttributeInfo dev.shadowsoffire.attributeslib.AttributesLib.getAttrInfo(net.minecraft.class_1320)'"_**

And turns out that, from version 0.2.1 to 0.2.2 you're missing the AttributesInfo.class file.

![imagen_2024-04-04_221519253](https://github.com/TheWinABagel/ZenithAttributes/assets/21013700/905ac74e-6e48-4a08-acda-57c2aeef37b1)

This is a small image but between the 0.2.1 (Right) and 0.2.2 (Left) versions, the folder \zenith_attributes-0.2.X\dev\shadowsoffire\attributeslib\util is missing said file.

I 'fixed' the error by downgrading into 0.2.1 and I no longer have said issue.

**Comment by TheWinABagel** [comment]
Yeah, I should have been more diligent with this. But latest zenith + attributes should work together
