### ISSUE TITLE
AEA Crit Damage default is 0.5, making Zenith crits not happen

### ISSUE THREAD

**Issue by Partonetrain** [TheWinABagel/ZenithAttributes#18]
The ZenithAttributes implementation of crit chance leaves the [crit damage value check the same value as it is in](https://github.com/TheWinABagel/ZenithAttributes/blob/master/src/main/java/dev/shadowsoffire/attributeslib/impl/AttributeEvents.java#L216) Apothic Attributes, even though the [AEA crit damage works differently than the Apothic Attributes crit damage attribute](https://github.com/DaFuqs/AdditionalEntityAttributes/blob/1.20/src/main/java/de/dafuqs/additionalentityattributes/AdditionalEntityAttributes.java#L21-L30).

In Apothic Attributes, the attribute defaults to 1.5, making crits happen because [this check is passed](https://github.com/Shadows-of-Fire/Apothic-Attributes/blob/1.20/src/main/java/dev/shadowsoffire/attributeslib/impl/AttributeEvents.java#L196)

I propose the while loop should check for ``critDmg > 0.0F``

**Comment by Partonetrain** [comment]
@TheWinABagel There's some more logic that needs to change 😅 As of right now, zenith crits **reduce** damage, as the rest of the code is still operating under the assumption that critDamage = 1.5. Would `float critDmg = 1 + (float) attacker.getAttributeValue(AdditionalEntityAttributes.CRITICAL_BONUS_DAMAGE);` work?

**Comment by TheWinABagel** [comment]
Oops, will put a release out fixing that rq, thanks for reporting!
