### ISSUE TITLE
Crash when preparing for world creation

### ISSUE THREAD

**Issue by Cataratas** [TheWinABagel/ZenithAttributes#2]
I know my modpack has a lot of mods, it's probably conflicting with something. I'm getting a crash upon trying to create a world after installing this mod.

[crash-2023-11-15_03.47.58-client.txt](https://github.com/TheWinABagel/ZenithAttributes/files/13361219/crash-2023-11-15_03.47.58-client.txt)

**Comment by TheWinABagel** [comment]
Oh whoops, I implemented a fix for that in zenith but not zenith attributes, fixed in 0.1.0
