### ISSUE TITLE
Elytras are infinite

### ISSUE THREAD

**Issue by shouxd** [TheWinABagel/ZenithAttributes#24]
Using Zenith 1.0.3 1.20.1 and Zenith Attributes 0.1.5 1.20.1 make Elytras have no durability, and so they never break making them last forever and rendering enchantments on them pointless

**Comment by Partonetrain** [comment]
Does this happen on 0.2.4?

**Comment by shouxd** [comment]
Hi sorry for the late reply but it seems like it does. I just tested this with Zenith 1.1.9, Zenith Attributes 0.2.4 and Fakerlib 0.1.3 and still same thing happens

**Comment by shouxd** [comment]
However, this behavior is only seen on the chest slot. I downloaded a trinket elytra slot mod and Elytra durability is normal when worn on that slot

**Comment by TheWinABagel** [comment]
This was fixed a while ago but I forgot to close the issue
