### ISSUE TITLE
Adds "Enables Elytra Flight" to Hephaestus' Equipment

### ISSUE THREAD

**Issue by archenovalis** [TheWinABagel/ZenithAttributes#29]
Disabling ZenithAttributes removes the elytra ability from the boots.
Enabling ZenithAttributes (Zenith disabled) adds it.

ZenithAttributes 0.2.4
Minecraft 1.20.1
Fabric 0.15.11
Prism 8.3
Win10
JavaJDK 17.0.11 x64

![image](https://github.com/TheWinABagel/ZenithAttributes/assets/141416512/9f8fae08-d6f1-4538-910e-4e446dd3cb19)

**Comment by TheWinABagel** [comment]
Should no longer happen with 0.2.5
