### ISSUE TITLE
Incompatibility with CraftTweaker

### ISSUE THREAD

**Issue by Cataratas** [TheWinABagel/ZenithAttributes#3]
I found a very strange bug, don't really know whats going on, but having both CraftTweaker and ZenithAttributes together makes all block drops vanish from existance, meaning when the player breaks a block, it's loot doesn't drop.

Removing either one of them solves the issue.
I don't know if this will be much of a help, but here's the log:
[latest.log](https://github.com/TheWinABagel/ZenithAttributes/files/13465964/latest.log)

**Comment by FunnyDev-github** [comment]
Exactly! I have the same problem😗

**Comment by Surpos0** [comment]
me too

**Comment by Partonetrain** [comment]
It seems to be _all loot tables_. This mod's loot attributes must be doing something unexpected.

**Comment by Partonetrain** [comment]
Still happening with zenith_attributes-0.1.2 and CraftTweaker-fabric-1.20.1-14.0.28

**Comment by Partonetrain** [comment]
The issue seems to be upstream, in porting-lib
(note that zenith_attributes-0.1.5 has loot-2.1.1102+1.20-entity-refactor.jar)
https://github.com/Fabricators-of-Create/Porting-Lib/issues/77
https://github.com/CraftTweaker/CraftTweaker/issues/1702

**Comment by Partonetrain** [comment]
[The issue has been fixed upstream](https://github.com/Fabricators-of-Create/Porting-Lib/issues/74), TheWinABagel will need to update PortingLib.

**Comment by TheWinABagel** [comment]
Updated to latest porting lib as of 0.2.0
