### ISSUE TITLE
Crash on game launch

### ISSUE THREAD

**Issue by Captivename** [TheWinABagel/ZenithAttributes#31]
Launcher: Curseforge
Zenith Attributes Version: 0.2.4 - Released 11/07/2024 (Two updates with same version & release date) 

Causing crash on start-up.

[crash-2024-07-11_14.20.01-client.txt](https://github.com/user-attachments/files/16177707/crash-2024-07-11_14.20.01-client.txt)

**Comment by muon-rw** [comment]
You’ll need to wait for Zenith to make a compatible release for the updated version

**Comment by TheWinABagel** [comment]
I accidentally published this early, Zenith 1.2.2 has compat for it.
