### ISSUE TITLE
Offhand stats arent getting added when dual wielding from Better combat in the Prominence II pack

### ISSUE THREAD

**Issue by Blazier1** [TheWinABagel/ZenithAttributes#36]
My main hand has +3 Luck, my offhand sword has +2 luck and my necklace has +1 luck, but my attributes show only 4 luck? 

![2024-10-10_23 49 24](https://github.com/user-attachments/assets/7a2751e5-efa0-4259-bdcf-8d2df1fa0ea8)
![2024-10-10_23 49 27](https://github.com/user-attachments/assets/869fa155-434c-4bda-8f96-70bb64758aa6)
![2024-10-10_23 49 48](https://github.com/user-attachments/assets/20a4f7eb-8b12-407b-a1a7-1aaf29149e2e)

**Comment by SiverDX** [comment]
Seems to work as intended, considering it says `When in Main Hand`

**Comment by Blazier1** [comment]
That's dumb..... so is there a way to get it to say when in offhand or when held? Even the Daggers say it. Cause If not an entire build based on dual wielding is just out of luck the stats of a slots because shields and focus items for fasters give you benefits but rogues and dual fighters are left with nothing

**Comment by SiverDX** [comment]
attribute modifiers on items are related to an equipment slot
(unless they are added without one then it'd just say `When worn` or sth. like that)

you'll need to ask the better combat dev to apply hand modifiers for both offhand and mainhand (for dual wielding)
or ask the modpack author to handle this themselves

**Comment by Blazier1** [comment]
Oh my bad. I thought this was related to you guys. I apologize.

Yahoo Mail: Search, Organize, Conquer 
 
  On Mon, Oct 14, 2024 at 12:39 AM, ***@***.***> wrote:   


attribute modifiers on items are related to an equipment slot

you'll need to ask the better combat dev to apply main hand modifiers to off hand as well (for dual wielding)
or ask the modpack author to handle this themselves

**Comment by Blazier1** [comment]
Will bring this to the proper attentions.
