### ISSUE TITLE
Hitting a mob crashes the game

### ISSUE THREAD

**Issue by jp-067** [TheWinABagel/ZenithAttributes#5]
Every time i hit a mob the world crashes.
[crash-2024-01-05_14.23.26-server.txt](https://github.com/TheWinABagel/ZenithAttributes/files/13843188/crash-2024-01-05_14.23.26-server.txt)

**Comment by Partonetrain** [comment]
backdate Pufferfish's Skills to 0.10 until ZenithAttributes updates to account for 0.11

**Comment by jp-067** [comment]
thanks a lot

**Comment by TheWinABagel** [comment]
fixed
