### ISSUE TITLE
UI bug with REI

### ISSUE THREAD

**Issue by tiagoacarvalho** [TheWinABagel/ZenithAttributes#7]
Description:
The panel for the attributes and the overlay for potion effects overlap when the effects are set to the left side by REI.
![2024-01-31_10 37 53](https://github.com/TheWinABagel/ZenithAttributes/assets/52931413/6f0fd9ef-14ef-440f-b226-9d1eea9539ab)

Putting the itens on the left makes it even worse.
![2024-01-31_10 41 00](https://github.com/TheWinABagel/ZenithAttributes/assets/52931413/93e19125-15a0-4104-a8a3-3c21ede5563e)

Expected behaviour:
While attribute panel is open, potion effects are hidden if they overlap.

Steps to reproduce:
Install mods
Get potion effects
On REI's config (the gear button next to the search bar on the bottom), go to display settings and toggle left side mob effects or toggle left side panel.
Open attribute panel
Observe mess.

**Comment by TheWinABagel** [comment]
Hmm... Not quite sure how to fix either of these issues without redoing a whole lot of stuff, which I quite frankly don't have the spoons for at the moment

**Comment by TheWinABagel** [comment]
Fixed with 0.2.3
I realized you could add exclusion zones for REI :P
