### ISSUE TITLE
Add config to disable potion tooltip

### ISSUE THREAD

**Issue by Partonetrain** [TheWinABagel/ZenithAttributes#8]
The way this mod adds potion tooltips is potentially dangerous, being a redirect mixin - it should be configurable in case users have another mod that does the same thing.

I'd PR this myself, but I still can't get ZenithAttributes into my IDE because I can't find FakerLib.

**Comment by TheWinABagel** [comment]
Would this be a mixin config option? Cause yeah I should add that... (apologies for the lack of response, have been busy with IRL stuff and other projects)

**Comment by TheWinABagel** [comment]
I don't have experience with making those but I can give it a shot
The config that I'm using currently loads too late for that afaik

**Comment by Partonetrain** [comment]
MixinLoadingPlugin can help with this (I think)

**Comment by Partonetrain** [comment]
Hmm, what's actually adding the description tooltip is [this line](https://github.com/TheWinABagel/ZenithAttributes/blob/master/src/main/java/dev/shadowsoffire/attributeslib/client/AttributesLibClient.java#L143), so the config would ideally disable that too

**Comment by TheWinABagel** [comment]
Added with 0.2.2

**Comment by Partonetrain** [comment]
Thanks!
