### ISSUE TITLE
Crash with newest Version of AdditionalEntityAttributes

### ISSUE THREAD

**Issue by DaFuqs** [TheWinABagel/ZenithAttributes#9]
Heya!

AdditionalEntityAttributes recently updated to add a new attribute and fix a few oversights of the past (my bad!)
In one breaking change, the CRITICAL_BONUS_DAMAGE is not added for all LivingEntities anymore, but only to players (Since only players usually deal crits while jumping).
[ZenithAttribs always assumed the attribute would be present for all entities](https://github.com/TheWinABagel/ZenithAttributes/blob/d127b6efe640b59473f0d10b3e3a29c3437258f1/src/main/java/dev/shadowsoffire/attributeslib/impl/AttributeEvents.java#L200) (a fair assumption!), this results in a crash with the newest version of AEA.

[The issue in the AEA repo has the full info](https://github.com/DaFuqs/AdditionalEntityAttributes/issues/28)

**Comment by TheWinABagel** [comment]
Ah, thanks. Fixed it in 0.2.0
